import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/prerequisites',
        'getting-started/first-launch',
        'getting-started/your-first-session',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/multi-session-grid',
        'features/session-history',
        'features/git-worktrees',
        'features/quick-actions',
        'features/terminal',
        'features/mcp-integration',
        'features/themes',
        'features/keyboard-shortcuts',
        'features/auto-update',
        'features/project-tabs',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: ['configuration/settings-overview', 'configuration/provider-settings'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/parallel-development', 'guides/troubleshooting'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture/overview'],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: ['contributing/quickstart'],
    },
    'changelog',
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
