name: 'Setup Project'
description: 'Common setup steps for CI workflows - checkout, Node.js, pnpm, dependencies, and native modules'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Configure Git for HTTPS
      shell: bash
      run: git config --global url."https://github.com/".insteadOf "git@github.com:"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build shared packages
      shell: bash
      run: pnpm build:packages
