export { AppearanceSection } from './AppearanceSection';
export { GithubSection } from './GithubSection';
export { McpSection } from './McpSection';
export { GeneralSection } from './GeneralSection';
export { WorktreesSection } from './WorktreesSection';
export { SessionsSection } from './SessionsSection';
export { QuickActionsSection } from './QuickActionsSection';
export { TerminalSection } from './TerminalSection';
export { NotificationsSection } from './NotificationsSection';
