import {
  Play,
  Square,
  Hammer,
  Wrench,
  Bug,
  FlaskConical,
  Rocket,
  Zap,
  Terminal,
  Server,
  Database,
  Package,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  FileCode,
  Folder,
  FolderOpen,
  Settings,
  Cog,
  Bot,
  Sparkles,
  ListTodo,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  RefreshCw,
  RotateCcw,
  Trash,
  Trash2,
  Search,
  Hash,
  Command,
  Boxes,
  Container,
  CloudUpload,
  CloudDownload,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  BarChart,
  PieChart,
  Activity,
  Globe,
  Code,
  Code2,
  Layers,
  TestTube,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  Clock,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated set of Lucide icon names available in the custom-command IconPicker.
 * Kept intentionally small (under 60) so the picker stays scannable. The
 * stored `icon` field on a CustomCommand is one of these names — but the
 * resolver below also handles unknown values by falling back to `Terminal`,
 * so old data continues to render after a release that prunes an icon.
 */
export const CUSTOM_COMMAND_ICON_NAMES = [
  'Play',
  'Square',
  'Hammer',
  'Wrench',
  'Bug',
  'FlaskConical',
  'Rocket',
  'Zap',
  'Terminal',
  'Server',
  'Database',
  'Package',
  'GitBranch',
  'GitCommit',
  'GitMerge',
  'GitPullRequest',
  'FileCode',
  'Folder',
  'FolderOpen',
  'Settings',
  'Cog',
  'Bot',
  'Sparkles',
  'ListTodo',
  'ArrowUp',
  'ArrowDown',
  'ArrowRight',
  'RefreshCw',
  'RotateCcw',
  'Trash',
  'Trash2',
  'Search',
  'Hash',
  'Command',
  'Boxes',
  'Container',
  'CloudUpload',
  'CloudDownload',
  'Lock',
  'Unlock',
  'Eye',
  'EyeOff',
  'BarChart',
  'PieChart',
  'Activity',
  'Globe',
  'Code',
  'Code2',
  'Layers',
  'TestTube',
  'ShieldCheck',
  'AlertTriangle',
  'CheckCircle2',
  'Clock',
] as const;

export type CustomCommandIconName = (typeof CUSTOM_COMMAND_ICON_NAMES)[number];

const ICON_MAP: Record<string, LucideIcon> = {
  Play,
  Square,
  Hammer,
  Wrench,
  Bug,
  FlaskConical,
  Rocket,
  Zap,
  Terminal,
  Server,
  Database,
  Package,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  FileCode,
  Folder,
  FolderOpen,
  Settings,
  Cog,
  Bot,
  Sparkles,
  ListTodo,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  RefreshCw,
  RotateCcw,
  Trash,
  Trash2,
  Search,
  Hash,
  Command,
  Boxes,
  Container,
  CloudUpload,
  CloudDownload,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  BarChart,
  PieChart,
  Activity,
  Globe,
  Code,
  Code2,
  Layers,
  TestTube,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  Clock,
};

export const DEFAULT_CUSTOM_COMMAND_ICON: CustomCommandIconName = 'Terminal';

/**
 * Resolve an icon name (string) to its Lucide component. Falls back to a
 * default icon (Terminal) when the name is unknown — needed because stored
 * data may reference an icon that has been pruned from the curated list.
 */
export function getCustomCommandIcon(name: string | undefined | null): LucideIcon {
  if (!name) return ICON_MAP[DEFAULT_CUSTOM_COMMAND_ICON];
  return ICON_MAP[name] ?? ICON_MAP[DEFAULT_CUSTOM_COMMAND_ICON];
}

/**
 * Whether an arbitrary string corresponds to one of the curated icons.
 */
export function isKnownCustomCommandIcon(name: string): name is CustomCommandIconName {
  return name in ICON_MAP;
}
